### ISSUE TITLE
Сыпется на одном тайтле.

### ISSUE THREAD

**Issue by Ujiipot** [shupkat/RanobeLib2Epub#5]
Привет! Работает на ура. Только 1 новеллой проблема возникла за долгое время.
https://ranobelib.me/ru/book/6778--tensei-shitara-kendeshita-novel?from=catalog

Когда доходит до главы 1308.1 - начинает сыпаться. Зацикливается. Вставил кусок который повторяется.
Сделал скрин. Повторяется каждый раз на этом моменте (пробовал 3 раза). Сама папка новеллы создаётся. Но содержимого нет.

С другими произведениями пока такого не встречал.

![vlcsnap-2024-07-09-10h32m21s629](https://github.com/shupkat/RanobeLib2Epub/assets/175086258/c7ac3ba6-a4ea-4022-b7f9-ee2c210cd3e5)

<details>
  <summary>Содержимое консоли</summary>

  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 469, in node_type
    raise ValueError(msg)
ValueError: Unknown node type: horizontalRule

Traceback (most recent call last):
  File "C:\Users\gonin\Downloads\RanobeLib2Epub-main\chapter_parser.py", line 55, in parse_chapter
    doc_node = Node.from_json(schema, json_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 357, in from_json
    content = Fragment.from_json(schema, json_data.get("content"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\fragment.py", line 270, in from_json
    return cls([schema.node_from_json(item) for item in value])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 457, in node_from_json
    return Node.from_json(self, json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 358, in from_json
    return schema.node_type(str(json_data["type"])).create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 469, in node_type
    raise ValueError(msg)
ValueError: Unknown node type: horizontalRule

Traceback (most recent call last):
  File "C:\Users\gonin\Downloads\RanobeLib2Epub-main\chapter_parser.py", line 55, in parse_chapter
    doc_node = Node.from_json(schema, json_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 357, in from_json
    content = Fragment.from_json(schema, json_data.get("content"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\fragment.py", line 270, in from_json
    return cls([schema.node_from_json(item) for item in value])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 457, in node_from_json
    return Node.from_json(self, json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 358, in from_json
    return schema.node_type(str(json_data["type"])).create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 469, in node_type
    raise ValueError(msg)
ValueError: Unknown node type: horizontalRule

</details>

**Comment by shupkat** [comment]
Исправил. Если заметите проблемы с форматированием откройте новый issue.
