### ISSUE TITLE
Ошибка при скачивании.

### ISSUE THREAD

**Issue by Ujiipot** [shupkat/RanobeLib2Epub#6]
Привет! Благодарю!
Нашась ещё новелла при скачивании которой аналогичная ошибка.))
https://ranobelib.me/ru/book/62850--akuyaku-reijo-wa-shomin-ni-totsugitai-novel?from=catalog
В переводе: 1 - Смена Октября. Глав переведено 137

![Снимок экрана 2024-07-09 180611](https://github.com/shupkat/RanobeLib2Epub/assets/175086258/43b3edc9-b9c4-44ac-b45f-4d32c2c34429)

<details>
  <summary>Содержимое консоли</summary>
Traceback (most recent call last):
  File "C:\Users\gonin\Downloads\RanobeLib2Epub-main\chapter_parser.py", line 55, in parse_chapter
    doc_node = Node.from_json(schema, json_content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 357, in from_json
    content = Fragment.from_json(schema, json_data.get("content"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\fragment.py", line 270, in from_json
    return cls([schema.node_from_json(item) for item in value])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 457, in node_from_json
    return Node.from_json(self, json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 357, in from_json
    content = Fragment.from_json(schema, json_data.get("content"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\fragment.py", line 270, in from_json
    return cls([schema.node_from_json(item) for item in value])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 457, in node_from_json
    return Node.from_json(self, json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\node.py", line 354, in from_json
    marks = [schema.mark_from_json(item) for item in json_data["marks"]]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\schema.py", line 463, in mark_from_json
    return Mark.from_json(self, json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonin\AppData\Local\Programs\Python\Python312\Lib\site-packages\prosemirror\model\mark.py", line 70, in from_json
    raise ValueError(msg)
ValueError: There is no mark type underline in this schema
</details>

**Comment by shupkat** [comment]
Сделал поддержку для подчёркнутого текста.
